# Site settings
title: 'Pofat Develops'
description: '#0x8badf00d ğŸ¤®'
keywords: 'iOS, Swift'
url: 'https://pofat.github.io'

nav: 
  Articles: '/'
  Tags: '/tags.html'
  Timeline: '/timeline.html'
  About: '/about.html'

# Me
author: true
name: 'Pofat Tseng'
NickName: 'æ³¢å­'
webtitle: 'Pofat Develops'
bio: 'æˆ‘æ˜¯ä¸€å€‹é–‹ç™¼è€…ï¼Œå–œæ­¡é–‹ç™¼ iOS ã€ç”¢å“èˆ‡è€åŠ›é‹å‹•èƒ½åŠ›ï¼Œå°æ–¼ Swift æœ‰æ„›'
about: true
aboutyou: 'æ¬²èªè­˜è‚¥å®…å¯ç”±ä¸‹æ–¹é€²å…¥'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon:
  github: 'https://github.com/pofat'
  Twitter: 'https://twitter.com/PofatTseng'
  twitch: ''

# pagination
paginate: 10
paginatepath: ['page:num']

# since
footer:
  since: 2019

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# highlighter: use rouge
highlighter: rouge
pygmentsTheme: 'pastie'

# Friend link
friends:
  jekyll: ''

# comment system
# disqus
disqus: true
disqus_url: 'https://pofat-dev.disqus.com/embed.js' # https://abc.disqus.com/embed.js
# livere
livere: false
livere_uid: ''
# Gitment
Gitment: false
Gitment_owner: ''  # github user
Gitment_repo: ''  # repo
client_id: ''  # OAuth Application client_id
client_secret: ''  # OAuth Application secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['twitter', 'facebook', 'linkedin']

# Baidu Analysis
baidu: false
baidu-url: ''
# GA
google: true
google-ID: 'UA-141693863-1'

# Blog header backup colors: It's not a site variable. This will be written in each post as a local variable
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
